site_name: "Principles of Artificial Intelligence Notes"
site_description: "Study notes based on Nils J. Nilsson"
site_author: "Pouya"

repo_url: "https://github.com/pouyatavakoli/AI-notes"
repo_name: "AI Notes on GitHub"

theme:
  name: material
  language: en
  icon:
    repo: fontawesome/brands/github
    logo: material/brain
  features:
    # Navigation & layout
    - navigation.instant
    - navigation.top
    - navigation.expand
    - navigation.tracking
    - navigation.hide
    - toc.integrate
    - toc.follow
    - navigation.footer
    - navigation.sections
    - navigation.tabs
    # Content & interaction
    - content.code.copy
    - content.tabs.link
    - content.tooltips
    - header.autohide
    - search.suggest
    - search.highlight
  palette:
    - scheme: default
      primary: indigo
      accent: deep purple
      toggle:
        icon: material/weather-night
        name: Switch to dark mode
    - scheme: slate
      primary: indigo
      accent: lime
      toggle:
        icon: material/weather-sunny
        name: Switch to light mode
  font:
    text: "Inter"
    code: "Fira Code"
  typography:
    text:
      line_height: 1.7
    headings:
      font_weight: 600

nav:
  - Home: index.md
  - Chapters:
      - "Chapter 1 - Production Systems": chapters/chapter1-production-systems.md
      - "Chapter 2 - Search and Control Strategies": chapters/chapter2-search-and-control-strategies.md
  - Glossary: summaries/glossary.md
  - About: about.md

markdown_extensions:
  - admonition
  - attr_list
  - toc:
      permalink: true
  - codehilite
  - footnotes
  - def_list
  - pymdownx.details
  - pymdownx.superfences
  - pymdownx.highlight
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.mark
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.tasklist
  - pymdownx.caret
  - pymdownx.emoji
  - pymdownx.betterem:
      smart_enable: all

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/pouyatavakoli
      name: GitHub
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/pouya-t/
      name: LinkedIn
  generator: false

extra_css:
  - styles/extra.css
